FROM golang:1.19 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o kaspa_exporter .

FROM alpine:latest
COPY --from=builder /app/kaspa_exporter /usr/local/kaspa_exporter
ENTRYPOINT [ "/usr/local/kaspa_exporter" ]